{% set name = "nannos" %}
{% set version = "2.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: a67970acc7eb9a342b6119d345f7b68d750d5866749907cf3538882e0eb31360


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.9, <2
    - scipy >=1.0
    - autograd >=1.4
    - matplotlib-base
    - shapely
    - joblib
    - colorlog
    - psutil
    - ipython
    - nlopt
    - pytorch           # [not win]
    - pytorch =*=cpu*   # [cuda_compiler_version == "None" and not win] 
    - pytorch =*=cuda*  # [cuda_compiler_version != "None" and not win] 
    - magma             # [not osx and not win]
    - jax               # [not win]
    - jaxlib            # [cuda_compiler_version == "None" and not win]
    - jaxlib =*=*cuda*  # [cuda_compiler_version != "None" and not win]
    - pyvista
    - ipywidgets
    - trame
    - trame-vuetify
    - trame-vtk
    - importlib_metadata   # [py<38]

test:
  imports:
    - {{ name }}
  source_files:
    - test/conda_test.py
  commands:
    - pytest -s -vv ./test/conda_test.py
  requires:
    - pytest

about:
  home: https://gitlab.com/nannos/nannos
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Fourier Modal Method for multilayer metamaterials'

  description: |
    Nannos is a Python package to solve Maxwell's equations in mono or 
    bi-periodic multilayer structures using the Fourier Modal Method. 
    It implements various formulations, automatic differentiation and 
    GPU acceleration.
  doc_url: https://{{ name }}.gitlab.io
  dev_url: https://gitlab.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - benvial
