{% set name = "nannos" %}
{% set version = "2.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: a67970acc7eb9a342b6119d345f7b68d750d5866749907cf3538882e0eb31360


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.9
    - scipy >=1.0
    - autograd >=1.6.2
    - matplotlib-base >=3.9.2
    - shapely >=2.0.6
    - joblib >=1.4.2
    - colorlog >=6.8.2
    - psutil >=6.0.0
    - ipython >=8.27.0
    - nlopt >=2.8.0
    - pytorch >=2.4.1   # [not win]
    - pytorch =*=cpu*   # [cuda_compiler_version == "None" and not win] 
    - pytorch =*=cuda*  # [cuda_compiler_version != "None" and not win] 
    - magma             # [not osx and not win]
    - jax >=0.4.31      # [not win]
    - jaxlib            # [cuda_compiler_version == "None" and not win]
    - jaxlib =*=*cuda*  # [cuda_compiler_version != "None" and not win]
    - pyvista >=0.44.0
    - ipywidgets >=8.1.5
    - trame >=3.6.5
    - trame-vuetify
    - trame-vtk

test:
  imports:
    - {{ name }}
  source_files:
    - test/conda_test.py
  commands:
    - pytest -s -vv ./test/conda_test.py
  requires:
    - pytest

about:
  home: https://gitlab.com/nannos/nannos
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'Fourier Modal Method for multilayer metamaterials'

  description: |
    Nannos is a Python package to solve Maxwell's equations in mono or 
    bi-periodic multilayer structures using the Fourier Modal Method. 
    It implements various formulations, automatic differentiation and 
    GPU acceleration.
  doc_url: https://{{ name }}.gitlab.io
  dev_url: https://gitlab.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - benvial
